# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "SPI Lab"
title:              "SPI Lab | Security Privacy Interaction Lab at the University of Michigan"
description:        "We are a privacy research group at the School of Information at the University of Michigan."


# URL
url:                https://spilab-umich.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "people"
    href:           "/people"
  - name:           "projects"
    href:           "/projects"
  - name:           "publications"
    href:           "/publication"
  - name:           "get involved"
    href:           "/join"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html

  projects:
    output: true
